[default]
APPNAME = "FOOTPRINT_PLANEJAMENTO_ESTRATEGICO"
APPNAME_LOG = "FOOTPRINT_PLANEJAMENTO_ESTRATEGICO.log"
APPNAME_TELA_LOGIN = "APP - PLANEJAMENTO ESTRATÉGICO"
APPNAME_TITLE = "FOOTPRINT - PLANEJAMENTO ESTRATÉGICO"
APPNAME_TITLE_ICON = ":world-map:"
LOGO_APP = "assets/itau.png"
STYLES_CSS = 'styles/style.css'

# CREDENTIALS
LIST_TYPE_AUTHENTICATOR = ["EXCEL", "SHAREPOINT"]
TYPE_AUTHENTICATOR = "EXCEL"
AUTHENTICATOR_BUTTON = "SHAREPOINT"
AUTHENTICATION_CREDENTIALS_INDEX = "email"
VALIDATOR_RENAME_CREDENTIALS = true
AUTHENTICATION_CREDENTIALS_INDEX_DICT_RENAME = {"USUARIO"="username", "EMAIL"="email", "NOME"="name", "TOKEN"="password", "GRUPO_ACESSO"="GRUPO_ACESSO"}

# SHAREPOINT
AUTHENTICATION_CREDENTIALS_SHAREPOINT = "credentials_bd/credentials.xlsx"
AUTHENTICATION_CONFIG_SHAREPOINT = "credentials/credentials.yaml"
BD_SHAREPOINT = "bd/BD_SHAREPOINT.db"

# EXCEL
AUTHENTICATION_CREDENTIALS_EXCEL = "credentials/credentials.xlsx"
AUTHENTICATION_CONFIG_EXCEL = "credentials/credentials.yaml"

# FORM LOGIN
FORM_NAME_USERNAME = "Email"
FORM_NAME_PASSWORD = "Senha"
FORM_NAME_BUTTON = "Entrar"

# DIRETÓRIO PARA SAVE DOS RESULTADOS
DIR_SAVE_RESULT = "resultados/RESULTADO_ESTRATEGICO.xlsx"

# DATAFRAMES
LIST_OPTIONS_DATAFRAME_EXPLORER = ["agstyle", "aggrid_default", "dataframe_explorer"]
OPTION_DATAFRAME_EXPLORER = "dataframe_explorer"

# COLUNAS DE FILTRO
COLUMN_MERCADO = "MERCADO"
FILTRO_MERCADO_VALUE_DEFAULT = "Todos"
COLUMN_REGIAO = "REGIÃO"
FILTRO_REGIAO_VALUE_DEFAULT = "Todas"
COLUMN_SUPT = "SUPT"
FILTRO_SUPT_VALUE_DEFAULT = "Todas"

# MAPA
MAP_ICON_DEFAULT = "assets/itau.png"
MAP_DICT_ICON_DEFAULT = {"VERMELHA"="assets/itau_vermelho.png", "AMARELA"="assets/itau_amarelo.png", "VERDE"="assets/itau_verde.png"}

[development]
DATA_DIR_AGENCIAS = "data/FOOTPRINT_PLANEJAMENTO_ESTRATEGICO.xlsx"
COLUMN_NUM_AGENCIA = "CÓDIGO AG"
VALIDATOR_ADD_LAYER = false # TORNANDO true, REMOVE A FEATURE DE MARKER CLUSTER
MAP_SAVE_FIGURE = true
MAP_LAYER_DEFAULT = "cartodbpositron"
MAP_SAVE_NAME = "PLOT_MAP_2.html"
VALIDATOR_MARKER_CLUSTER = true
COLUMN_MARKER_CLUSTER = "MERCADO"

# PARÂMETROS USADOS NA SELEÇÃO DO MAPA
COLUMN_STATUS = "STATUS"
COLUMN_LATITUDE = "LATITUDE"
COLUMN_LONGITUDE = "LONGITUDE"
MAP_COLUMN_TOOLTIP = "CÓDIGO AG"
MAP_COLUMN_HEADER = "ENDEREÇO"

# PARÂMETROS DE ESTRATÉGIAS POSSÍVEIS
OPTIONS_ESTRATEGIA = ["Manter estratégia", "Encerrar", "Manter", "Espaço Itaú"]

# COLUNA PARA SALVAR AS OPÇÕES DESEJADAS
COL_SAVE_ACTION = "ESTRATÉGIA SELECIONADA"