[default]
APPNAME = "FOOTPRINT_PLANEJAMENTO_ESTRATEGICO"
APPNAME_LOG = "FOOTPRINT_PLANEJAMENTO_ESTRATEGICO.log"
APPNAME_TELA_LOGIN = "APP - PLANEJAMENTO ESTRATÉGICO"
APPNAME_TITLE = "FOOTPRINT - PLANEJAMENTO ESTRATÉGICO"
APPNAME_TITLE_ICON = ":world-map:"
LOGO_APP = "assets/itau.png"
STYLES_CSS = 'styles/style.css'

# CREDENTIALS
AUTHENTICATION_CREDENTIALS = "credentials/credentials.xlsx"
AUTHENTICATION_CONFIG = "credentials/credentials.yaml"
AUTHENTICATION_CREDENTIALS_INDEX = "email"
VALIDATOR_RENAME_CREDENTIALS = true
AUTHENTICATION_CREDENTIALS_INDEX_DICT_RENAME = {"USUARIO"="username", "EMAIL"="email", "NOME"="name", "TOKEN"="password", "GRUPO_ACESSO"="GRUPO_ACESSO"}

# FORM LOGIN
FORM_NAME_USERNAME = "Email"
FORM_NAME_PASSWORD = "Senha"
FORM_NAME_BUTTON = "Entrar"

# DIRETÓRIO PARA SAVE DOS RESULTADOS
DIR_SAVE_RESULT = "resultados/RESULTADO_ESTRATEGICO.xlsx"

# DATAFRAMES
LIST_OPTIONS_DATAFRAME_EXPLORER = ["agstyle", "aggrid_default"]
OPTION_DATAFRAME_EXPLORER = "aggrid_default"

# MAPA
MAP_ICON_DEFALT = "assets/itau.png"
MAP_DICT_ICON_DEFAULT = {"VERMELHA"="assets/itau_vermelho.png", "AMARELA"="assets/itau_amarelo.png", "VERDE"="assets/itau_verde.png"}

[development]
DATA_DIR_AGENCIAS = "data/FOOTPRINT_PLANEJAMENTO_ESTRATEGICO.xlsx"
COLUMN_NUM_AGENCIA = "CÓDIGO AG"
VALIDATOR_ADD_LAYER = false # TORNANDO true, REMOVE A FEATURE DE MARKER CLUSTER
MAP_SAVE_FIGURE = true
MAP_LAYER_DEFAULT = "cartodbpositron"
MAP_SAVE_NAME = "PLOT_MAP.html"
VALIDATOR_MARKER_CLUSTER = true
COLUMN_MARKER_CLUSTER = "MERCADO"

# PARÂMETROS USADOS NA SELEÇÃO DO MAPA
COLUMN_STATUS = "STATUS"
COLUMN_LATITUDE = "LATITUDE"
COLUMN_LONGITUDE = "LONGITUDE"
MAP_COLUMN_TOOLTIP = "CÓDIGO AG"
MAP_COLUMN_HEADER = "ENDEREÇO"

# PARÂMETROS DE ESTRATÉGIAS POSSÍVEIS
OPTIONS_ESTRATEGIA = ["Encerrar", "Manter", "Espaço Itaú"]

# COLUNA PARA SALVAR AS OPÇÕES DESEJADAS
COL_SAVE_ACTION = "ESTRATÉGIA SELECIONADA"